# numpy 배열 생성

In [2]:
import numpy as np
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [3]:
v1 = np.arange(5)
print(v1)

[0 1 2 3 4]


In [5]:
v2 = np.arange(1,10,2,dtype=int) # dtype 생략해도 됨
print(v2)

[1 3 5 7 9]


In [6]:
v3 = np.arange(3.5,10.5,2,dtype=float)
print(v3)

[3.5 5.5 7.5 9.5]


In [7]:
v4 = np.arange(1,10,2)**2
print(v4)

[ 1  9 25 49 81]


In [9]:
v5 = np.arange(1,10,2)**3
print(v5)

[  1  27 125 343 729]


# 행렬 만들기
## np.reshpae(차원,행,열,order='C'(기본값,행->열->차원)or'F'(차원->열->행))

In [10]:
v1 = np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
v2 = v1.reshape(2,6)
print(v2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [12]:
v3 = v1.reshape(2,6,order='F')
print(v3)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [3]:
# np.dot(변수명,변수명): 행렬 연산
v1 = np.arange(1,5).reshape(2,2)
print(np.add(v1,v1))
print(np.subtract(v1,v1))
print(np.multiply(v1,v1))
print(np.dot(v1,v1))

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


# 다차원 배열 만들기

In [14]:
v1 =np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [17]:
v2 = v1.reshape(2,3,2,order='F')
print(v2)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [7]:
v3 = np.arange(3.5,10.5,2,dtype=float)
print(v3)
print(np.amax(v3))
print(v3.dtype)

[3.5 5.5 7.5 9.5]
9.5
float64


In [9]:
v4 = np.arange(1,5).reshape(2,2)
print(v4)
print(np.amin(v4))
print(v4.shape)

[[1 2]
 [3 4]]
1
(2, 2)
